development:
  adapter: postgresql
  encoding: unicode
  database: terrance_email
  pool: 5
  username: gschool
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: terrance_email_test
  pool: 5
  username: gschool
  password:
